[tasks.strip]
command = "riscv32-unknown-elf-strip"
args = ["target/riscv32i-unknown-none-elf/release/embedded"]

[tasks.objcopy]
command = "riscv32-unknown-elf-objcopy"
args = [
    "-O",
    "binary",
    "target/riscv32i-unknown-none-elf/release/embedded",
    "target/riscv32i-unknown-none-elf/release/embedded.bin",
]
dependencies = ["strip"]

[tasks.objdump]
command = "riscv32-unknown-elf-objdump"
args = [
    "-O",
    "binary",
    "target/riscv32i-unknown-none-elf/release/embedded",
    "target/riscv32i-unknown-none-elf/release/embedded.s",
]
dependencies = ["strip"]
