[tasks.strip]
command = "riscv32-unknown-elf-strip"
args = ["target/riscv32i-unknown-none-elf/release/embedded_blossom"]

[tasks.objcopy]
command = "riscv32-unknown-elf-objcopy"
args = [
    "-O",
    "binary",
    "target/riscv32i-unknown-none-elf/release/embedded_blossom",
    "target/riscv32i-unknown-none-elf/release/embedded_blossom.bin",
]
dependencies = ["strip"]

[tasks.objdump]
script = "riscv32-unknown-elf-objdump -d target/riscv32i-unknown-none-elf/release/embedded_blossom > target/riscv32i-unknown-none-elf/release/embedded_blossom.s"
dependencies = ["strip"]

[tasks.embedded]
dependencies = ["objcopy", "objdump"]

# debug commands

[tasks.debug-strip]
command = "riscv32-unknown-elf-strip"
args = ["target/riscv32i-unknown-none-elf/debug/embedded_blossom"]

[tasks.debug-objcopy]
command = "riscv32-unknown-elf-objcopy"
args = [
    "-O",
    "binary",
    "target/riscv32i-unknown-none-elf/debug/embedded_blossom",
    "target/riscv32i-unknown-none-elf/debug/embedded_blossom.bin",
]
dependencies = ["debug-strip"]

[tasks.debug-objdump]
script = "riscv32-unknown-elf-objdump --show-all-symbols --inlines -D target/riscv32i-unknown-none-elf/debug/embedded_blossom > target/riscv32i-unknown-none-elf/debug/embedded_blossom.s"
dependencies = ["debug-strip"]

[tasks.debug-embedded]
dependencies = ["debug-objcopy", "debug-objdump"]
